runtime: php
env: flex

runtime_config:
  document_root: ./

handlers:
- url: /
  script: index.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /src
  static_dir: src

- url: /vendor/bootstrap/js
  static_dir: vendor/bootstrap/js

- url: /vendor/jquery
  static_dir: vendor/jquery

# - url: /(.*\.js)
#   mime_type: text/javascript
#   static_files: vendor/\1
#   upload: vendor/(.*\.js)

# - url: /vendor/font-awesome/css/font-awesome.min.css
#   static_files: vendor/font-awesome/css/font-awesome.min.css
#   upload: vendor/font-awesome/css/font-awesome.min.css

# - url: /vendor/bootstrap/js/bootstrap.bundle.min.js
#   static_files: vendor/bootstrap/js/bootstrap.bundle.min.js
#   upload: vendor/bootstrap/js/bootstrap.bundle.min.js

# - url: /vendor/jquery-easing/jquery.easing.min.js
#   static_files: vendor/jquery-easing/jquery.easing.min.js
#   upload: vendor/jquery-easing/jquery.easing.min.js

# - url: /vendor/autoload.php
#   static_files: vendor/autoload.php
#   upload: vendor/autoload.php

## Uncomment for Cloud SQL
# beta_settings:
#   cloud_sql_instances: "INSTANCE_CONNECTION_NAME"

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
